# -*- coding: utf-8 -*-
"""uts_cerdas_buat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NEHUhQQBDcS5zwKVj7S1-5sYnOoNXoZR

No. 1
"""

import statistics
from fractions import Fraction as F
from decimal import Decimal as D

age = [
        19,19,19,20,20,21,21,21,21,21,
        21,22,22,22,22,22,23,23,23,24,
        24,24,25,26,26,26,28,28,29,31,
        31,31,32,34,34,37,40,43,50,52,
        57,19,20,21,22,22,22,22,23,24,
        24,24,25,25,27,29,30,30,31,32,
        39
]
 
print("mean   : " , statistics.mean(age))
print("median : " , statistics.median(age))

"""No. 2"""

import statistics
import matplotlib.pyplot as plot
from fractions import Fraction as F
from decimal import Decimal as D

age = [
        19,19,19,20,20,21,21,21,21,21,
        21,22,22,22,22,22,23,23,23,24,
        24,24,25,26,26,26,28,28,29,31,
        31,31,32,34,34,37,40,43,50,52,
        57,19,20,21,22,22,22,22,23,24,
        24,24,25,25,27,29,30,30,31,32,
        39
]

plt.xlabel('Usia')
plt.ylabel('Jumlah')
bin_width = 10
kelompok_interval = range(0,100 + bin_width,bin_width)
plot.hist(age, kelompok_interval)

print("%.0f%%" % (100 * 1/3))

"""No. 4"""

import numpy

pubtran = [
        90,10,5,0,25,0,0,5,70,0,
        0,70,90,50,0,0,0,0,0,0,
        0,0,25,100,0,5,2,0,0,100,
        0,0,5,0,30,0,0,0,0,0,
        10,0,100,0,5,0,0,0,10,0,
        0,25,25,55,15,0,100,30,50,0,
        0,
]

x = numpy.std(pubtran)
print(x)

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
# from sklearn.linear_model import LinearRegressiondf 
from sklearn.linear_model import LinearRegression
pd.DataFrame([
              [151,63],[174,81],[138,56],[186,91],
              [128,47],[136,57],[179,76],[163,72],
              [152,62],[131,48]
            ])

df.columns = ['x', 'y']
x_train = df['x'].values[:,np.newaxis]
y_train = df['y'].valueslm = LinearRegression()
lm.fit(x_train,y_train) 

print('Coefficient : ' + str(lm.coef_))
print('Intercept : ' + str(lm.intercept_))
x_test = [[170],[171]] 
lm.predict(x_test) 
print(p)

pb = lm.predict(x_train)
dfc = pd.DataFrame({'x': df['x'],'y':pb})
plt.scatter(df['x'],df['y'])
plt.plot(dfc['x'],dfc['y'],color='red',linewidth=1)
plt.xlabel('Tinggi dalam cm')
plt.ylabel('Berat dalam Kg')
plt.show()

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn import linear_model
df = pd.DataFrame([
                    [151,63],[174,81],[138,56],[186,91],
                    [128,47],[136,57],[179,76],[163,72],
                    [152,62],[131,48]
                  ])

df.columns = ['x', 'y']
x_train = df['x'].values[:, np.newaxis]
y_train = df['y'].values
# lm = LinearRegression()
lm.fit(x_train, y_train)

print('Coefficient : ' + str(lm.coef_))
print('Intercept : ' + str(lm.intercept_))
x_test = [[170],[171]] 
p = lm.predict(x_tes)
print(p)
print("")


pb = lm.predict(x_train)
dfc = pd.DataFrame({'x': df['x'],'y':pb})
plt.scatter(df['x'],df['y'])
plt.plot(dfc['x'],dfc['y'],color='red',linewidth=1)
plt.xlabel('Tinggi dalam cm')
plt.ylabel('Berat dalam Kg')
plt.show()